AllCops:
  TargetRubyVersion: 2.5

Layout/EndOfLine:
  EnforcedStyle: lf

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
  Enabled: true